MonashBooks-war/src/java/MonashBook/BookController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MonashBook;

import MonashBook.ejb.EntityManageBean;
import MonashBook.entity.Book;
import MonashBook.entity.BookCopy;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;

/**
 *
 * @author stephen
 */
@Named(value = "bookController")
@SessionScoped
public class BookController implements Serializable {

    @EJB
    EntityManageBean emb;
    private Book book;
    private ArrayList<String> categoryList;
    /**
     * Creates a new instance of BookController
     */
    public BookController() {
        book = new Book();
        categoryList = new ArrayList<String>();
        categoryList.add("Business");
        categoryList.add("Technical");
        categoryList.add("Fiction");
        categoryList.add("Nonfiction");
        categoryList.add("Special Interest");
        categoryList.add("Young Readers");
        categoryList.add("Travel");
    }

    public ArrayList<String> getCategoryList() {
        return categoryList;
    }

    public void setCategoryList(ArrayList<String> categoryList) {
        this.categoryList = categoryList;
    }
    
    public List<BookCopy> getBookCopysFromBook(Book bo) {
        this.book = bo;
        List<BookCopy> bookCopy;
        bookCopy = new ArrayList<BookCopy>();
        for (Book b : emb.getBooks()) {
            if (b.getISBN().equals(book.getISBN())) {
                bookCopy = b.getBookCopyList();
            }
        }
        return bookCopy;
    }
    
    public Book getBook() {
        return book;
    }

    public String readBook(Book b) {
        this.book = b;
        return "bookDetail";
    }

    public String viewBook(Book b) {
        this.book = b;
        return "loanbook";
    }
    
    public String setupCreate() {
        book = new Book();
        return "manageBook";
    }

    public String create() {
        book.setImageUrl("../resources/image/02.jpg");
        emb.createBook(book);
        return "index";
    }

    public String update() {
        emb.updateBook(book);
        return "index";
    }

    public String delete(Book b) {
        emb.deleteBook(b);
        return "index";
    }
    
    public String deleteBookCopy(Book b, BookCopy bc) {
        //b.getBookCopyList()
        emb.deleteBookCopy(bc);
        return "bookDetail";
    }

    public List<Book> getBooks() {
        return emb.getBooks();
    }
}

MonashBooks-war/src/java/MonashBook/LoanController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MonashBook;

import Helper.Converter;
import MonashBook.ejb.EntityManageBean;
import MonashBook.entity.BookCopy;
import MonashBook.entity.Customer;
import MonashBook.entity.Loan;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.Dependent;
import javax.faces.context.FacesContext;

/**
 *
 * @author stephen
 */
@Named(value = "loanController")
@Dependent
public class LoanController {
    
    @EJB
    EntityManageBean emb;
    private Loan loan;
    private Customer cust;
    private BookCopy book;
    private Long bookCopyID;
    private String name;
    private int days;

    /**
     * Creates a new instance of LoanController
     */
    public LoanController() {
        loan = new Loan();
    }

    public int getDays() {
        return days;
    }

    public void setDays(int days) {
        this.days = days;
    }

    public Long getBookCopyID() {
        return bookCopyID;
    }

    public void setBookCopyID(Long bookCopyID) {
        this.bookCopyID = bookCopyID;
    }

    public String getName() {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        name = facesContext.getExternalContext().getRemoteUser();
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public String setupCreate() {
        loan = new Loan();
        return "loanbook";
    }
    
    public String delete(Loan l) {
        emb.deleteLoan(l);
        return "index";
    }
    
    public String create(Long id) {
        setBookCopyID(id);
        for (Customer c: emb.getCustomers()) {
            if (c.getUsername().equals(getName())) {
                cust = c;
            }
        }
        for (BookCopy b: emb.getBookCopys()) {
            if (b.getId() == bookCopyID) {
                book = b;
            }
        }
        if (book.getAvailability().equals("not Available")) {
            return "booknotavaliable";
        }else{
            days = 7;
            loan.setLoanDate(Converter.getCurrentDate());
            loan.setExpectReturnDate(Converter.getExpectReturnDate(days));
            loan.setReturnDate(null);
            loan.setLentBookCopy(book);
            loan.setBookForUser(cust);
            book.getBookLent().add(loan);
            book.setAvailability("not Available");
            cust.getUserLentBook().add(loan);
            emb.createLoan(loan);
            emb.updateBookCopy(book);
            return "loanbook";
        }
    }
    
    public String getFormatDate(Date d) {
        return Converter.convertDate(d);
    }
    
    public String returnBook(Long loanid) {
        for (Loan l : emb.getLoans()) {
            if (l.getId() == loanid) {
                loan = l;
            }
        }
        for (BookCopy bc : emb.getBookCopys()) {
            if (bc.getId() == loan.getLentBookCopy().getId()) {
                book = bc;
            }
        }
        book.setAvailability("available");
        loan.setReturnDate(Converter.getCurrentDate());
        emb.updateBookCopy(book);
        emb.updateLoan(loan);
        
        return "returnbook";
    }
    
    public List<Loan> getLoans() {
        return emb.getLoans();
    }
    
    public List<Loan> getLoansForCustomer() {
        List<Loan> loans = new ArrayList<Loan>();
        for (Loan l : emb.getLoans()) {
            if (l.getBookForUser().getUsername().equals(getName())) {
                loans.add(l);
            }
        }
        return loans;
    }

    public List<Loan> getFinishLoansForCustomer() {
        List<Loan> finishedLoans = new ArrayList<Loan>();
        for (Loan l : emb.getLoans()) {
            if (l.getBookForUser().getUsername().equals(getName()) && l.getReturnDate() != null) {
                    finishedLoans.add(l);
            }
        }
        return finishedLoans;
    }
    
    public List<Loan> getProcessingLoansForCustomer() {
        List<Loan> processingLoans = new ArrayList<Loan>();
        for (Loan l : emb.getLoans()) {
            if (l.getBookForUser().getUsername().equals(getName()) && l.getReturnDate() == null) {
                    processingLoans.add(l);
            }
        }
        return processingLoans;
    }
}

MonashBooks-war/web/user/SearchResult.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="usernav.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="maincontent">
                    <h1>User Page</h1>
                    <ui:repeat value="#{searchController.resultBookList}" var="book" varStatus="status">
                        <div class="imagecontent">
                            <div class="image">
                                <img src="#{book.imageUrl}"></img>
                            </div>
                            <div class="titlecon">
                                Title: #{book.title}&#160;&#160;Author: #{book.author}
                                <br/>
                                Publisher: #{book.publisher}&#160;&#160;Category: #{book.category}
                            </div>
                            <div class="description">
                                #{book.description}<br/>
                                <h:form>
                                    <h:commandButton action="#{bookController.viewBook(book)}" value="Loan A Copy" />
                                    <br/>
                                    <h:commandButton action="#{customerController.markBook(book)}" value="Mark A Book" />
                                    <h:commandButton action="#{commentController.readBook(book)}" value="Comment Book"/>
                                </h:form>
                            </div>
                        </div>
                        <hr/>
                    </ui:repeat>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBooks-war/web/user/addComment.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Add Comment</title>
    </h:head>
    <h:body>

        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="usernav.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="maincontent">
                    <h:form>
                        <div class="imagecontent">
                            <div class="image">
                                <img src="#{commentController.book.imageUrl}"></img>
                            </div>
                            <div class="titlecon">
                                #{commentController.book.title}   #{commentController.book.author}
                            </div>
                            <div class="description">
                                #{commentController.book.description}<br/>

                            </div>
                        </div>
                        <h:dataTable value="#{commentController.book.booksComment}" var="comment">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="customer"/>
                                </f:facet>
                                <h:outputText value="#{comment.customerComment.username}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Comment Content"/>
                                </f:facet>
                                <h:outputText value="#{comment.comment}"/>
                            </h:column>
                        </h:dataTable>
                        <h:outputLabel value="Comment:" for="comment" />
                        <h:inputTextarea id="comment" value="#{commentController.commentContent}"
                                         title="comment" />
                        <br/>
                        <h:commandButton action="#{commentController.create()}" value="Add Comment"></h:commandButton>
                    </h:form>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBooks-war/web/user/booknotavaliable.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>error</title>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="usernav.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="maincontent">
                    <h:form>
                        <p>Sorry!! You can not loan a book not avaliable</p>
                        <h:link outcome="loanbook">back to loan</h:link>
                    </h:form>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBooks-war/web/user/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>User InterFace</title>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="usernav.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="maincontent">
                    <h1>User Page</h1>
                    <ui:repeat value="#{bookController.books}" var="book" varStatus="status">
                        <div class="imagecontent">
                            <div class="image">
                                <img src="#{book.imageUrl}"></img>
                            </div>
                            <div class="titlecon">
                                Title: #{book.title}&#160;&#160;&#160;&#160;&#160;&#160;&#160;Author: #{book.author}
                                <br/>
                                Publisher: #{book.publisher}&#160;&#160;&#160;&#160;&#160;&#160;Category: #{book.category}
                            </div>
                            <div class="description">
                                #{book.description}<br/>
                                <h:form>
                                    <h:commandButton action="#{bookController.viewBook(book)}" value="Loan A Copy" />
                                    <br/>
                                    <h:commandButton action="#{customerController.markBook(book)}" value="Mark A Book" />
                                    <h:commandButton action="#{commentController.readBook(book)}" value="Comment Book"/>
                                </h:form>
                            </div>
                        </div>
                        <hr/>
                    </ui:repeat>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBooks-war/web/user/loanbook.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Book Detail</title>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="usernav.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="maincontent">
                    <h:form>
                        <h1><h:outputText value="Create/Edit Book"/></h1>
                        <h:panelGrid columns="2">
                            <h:outputLabel value="Title:" for="title" />
                            <h:outputLabel value="#{bookController.book.title}" for="Title" />
                            <h:outputLabel value="Author:" for="author" />
                            <h:outputLabel id="author" value="#{bookController.book.author}"
                                         title="author" />
                            <h:outputLabel value="Description:" for="description" />
                            <h:outputLabel id="description" value="#{bookController.book.description}"
                                         title="description" />
                            <h:outputLabel value="ISBN:" for="ISBN" />
                            <h:outputLabel id="ISBN" value="#{bookController.book.ISBN}"
                                         title="ISBN" />
                            <h:outputLabel value="detail" for="detail" />
                            <h:outputLabel id="detail" value="#{bookController.book.publisher}"
                                         title="detail" />
                            <h:outputLabel value="version" for="version" />
                            <h:outputLabel id="version" value="#{bookController.book.version}"
                                         title="version" />
                            <h:outputLabel value="Category:" for="category" />
                            <h:outputLabel value="#{bookController.book.category}" for="category" />
                        </h:panelGrid>
                        <h:commandButton id="back" value="Back" action="index"/>

                        <h1><h:outputText value="Displaying BookCopys"/></h1>
                        <h:dataTable value="#{bookCopyController.getBookCopysForOneBook(bookController.book.id)}" var="bookcopy">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Copy ID"/>
                                </f:facet>
                                <h:outputText value="#{bookcopy.id}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Copy ID"/>
                                </f:facet>
                                <h:outputText value="#{bookcopy.availability}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Copy ID"/>
                                </f:facet>
                                <h:outputText value="#{bookcopy.bookCopy.title}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Actions"/>
                                </f:facet>
                                <h:commandButton action="#{loanController.create(bookcopy.id)}" value="Loan this Book" />
                            </h:column>
                        </h:dataTable>
                        <h:commandButton action="index" value="Back" />
                    </h:form>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBooks-war/web/user/managePreference.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Customer Preference</title>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="usernav.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="maincontent">
                    <h1>Marked Book</h1>
                    <ui:repeat value="#{customerController.markedBooks}" var="book" varStatus="status">
                        <div class="imagecontent">
                            <div class="image">
                                <img src="#{book.imageUrl}"></img>
                            </div>
                            <div class="titlecon">
                                #{book.title}   #{book.author}
                            </div>
                            <div class="description">
                                #{book.description}<br/>
                                <h:form>
                                    <h:commandButton action="#{bookController.viewBook(book)}" value="Loan A Copy" />
                                    <br/>
                                    <h:commandButton action="#{customerController.unmarkBook(book)}" value="Unmark Book" />
                                    <h:commandButton action="#{commentController.readBook(book)}" value="Comment Book"/>
                                </h:form>
                            </div>
                        </div>
                        <hr/>
                    </ui:repeat>
                    <hr/>
                    <h1>Unmarked Book</h1>
                    <ui:repeat value="#{customerController.normalBooks}" var="book" varStatus="status">
                        <div class="imagecontent">
                            <div class="image">
                                <img src="#{book.imageUrl}"></img>
                            </div>
                            <div class="titlecon">
                                #{book.title}   #{book.author}
                            </div>
                            <div class="description">
                                #{book.description}<br/>
                                <h:form>
                                    <h:commandButton action="#{bookController.viewBook(book)}" value="Loan A Copy" />
                                    <br/>
                                    <h:commandButton action="#{customerController.markBook(book)}" value="Mark Book" />
                                    <h:commandButton action="#{commentController.readBook(book)}" value="Comment Book"/>
                                </h:form>
                            </div>
                        </div>
                        <hr/>
                    </ui:repeat>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBooks-war/web/user/returnbook.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Return Book</title>
    </h:head>
    <h:body>
        <ui:composition template="../masterpage.xhtml">
            <ui:define name="header">
                <ui:include src="usernav.xhtml" />
            </ui:define>
            <ui:define name="content">
                <div id="maincontent">
                    <h:form>
                        <h1><h:outputText value="Finish Loan"/></h1>
                        <h:dataTable value="#{loanController.finishLoansForCustomer}" var="loan">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Customer"/>
                                </f:facet>
                                <h:outputText value="#{loan.bookForUser.username}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Customer"/>
                                </f:facet>
                                <h:outputText value="#{loan.lentBookCopy.bookCopy.title}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Loan Date"/>
                                </f:facet>
                                <h:outputText value="#{loan.loanDate}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Expect Return Date"/>
                                </f:facet>
                                <h:outputText value="#{loan.expectReturnDate}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Return Date"/>
                                </f:facet>
                                <h:outputText value="#{loan.returnDate}"/>
                            </h:column>
                        </h:dataTable>
                        <h:commandButton action="index" value="back" />
                        <hr/>
                        <h1><h:outputText value="Processing Loan"/></h1>
                        <h:dataTable value="#{loanController.processingLoansForCustomer}" var="loan">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Customer"/>
                                </f:facet>
                                <h:outputText value="#{loan.bookForUser.username}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Customer"/>
                                </f:facet>
                                <h:outputText value="#{loan.lentBookCopy.bookCopy.title}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Loan Date"/>
                                </f:facet>
                                <h:outputText value="#{loan.loanDate}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Expect Return Date"/>
                                </f:facet>
                                <h:outputText value="#{loan.expectReturnDate}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Actions"/>
                                </f:facet>
                                <h:commandButton action="#{loanController.returnBook(loan.id)}" value="return this Book" />
                            </h:column>
                        </h:dataTable>
                    </h:form>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBooks-war/web/user/usernav.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>User</title>
    </h:head>
    <h:body>
        <ui:composition>
            <div id="navbar">
                <ul>
                    <li><b>Welcome : </b>#{customerController.currentUsername}</li>
                    <li>
                        <h:form>
                            <h:commandLink action="index" >
                                Home
                            </h:commandLink>
                        </h:form>
                    </li>
                    <li>
                        <h:form>
                            <h:commandLink action="returnbook" >
                                Return Book
                            </h:commandLink>
                        </h:form>
                    </li>
                    <li>
                        <h:form>
                            <h:commandLink action="#{customerController.divideBooks()}" >
                                Manage Preference
                            </h:commandLink>
                        </h:form>
                    </li>
                    <li>
                        <h:form>
                            <h:commandLink action="#{indexController.logOut()}" >
                                Logout
                            </h:commandLink>
                        </h:form>
                    </li>
                    <li>
                        <h:form>
                            <h:inputText id="searchBoxInput" value="#{searchController.keyWords}"/>
                            <h:commandButton id="submit" value="Search" 
                                             action="#{searchController.searchBook()}">
                            </h:commandButton>
                        </h:form>
                    </li>
                </ul>
            </div>
        </ui:composition>
    </h:body>
</html>